# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='task.proto',
  package='pbnavitia',
  serialized_pb='\n\ntask.proto\x12\tpbnavitia\")\n\x04Task\x12!\n\x06\x61\x63tion\x18\x01 \x02(\x0e\x32\x11.pbnavitia.Action*#\n\x06\x41\x63tion\x12\n\n\x06RELOAD\x10\x00\x12\r\n\tHEARTBEAT\x10\x03')

_ACTION = descriptor.EnumDescriptor(
  name='Action',
  full_name='pbnavitia.Action',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='RELOAD', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='HEARTBEAT', index=1, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=68,
  serialized_end=103,
)


RELOAD = 0
HEARTBEAT = 3



_TASK = descriptor.Descriptor(
  name='Task',
  full_name='pbnavitia.Task',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='action', full_name='pbnavitia.Task.action', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=25,
  serialized_end=66,
)

_TASK.fields_by_name['action'].enum_type = _ACTION
DESCRIPTOR.message_types_by_name['Task'] = _TASK

class Task(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TASK
  
  # @@protoc_insertion_point(class_scope:pbnavitia.Task)

# @@protoc_insertion_point(module_scope)
